### ISSUE TITLE
I can not find the .dll on macOS

### ISSUE THREAD

**Issue by lepustse** [Silverfeelin/spotdl-handler#3]
About the installation steps：

> 1 - Application
Move the folder SpotifyDownloader to /Applications/SpotifyDownloader
The result should look like this: /Applications/SpotifyDownloader/SpotifyDownloader.dll.
Call the application once to configure it with dotnet /Applications/SpotifyDownloader/SpotifyDownloader.dll.

how did SpotifyDownloader.dll file appear?

**Comment by Silverfeelin** [comment]
Are you downloading the release zip from the releases page? The dll and all other required files are in the Spotify downloader folder.

**Comment by Silverfeelin** [comment]
https://github.com/Silverfeelin/spotdl-handler/releases

**Comment by lepustse** [comment]
hi, i got spotdl-handler by clonging.but i can not find any .dll.

**Comment by Silverfeelin** [comment]
Thatll

**Comment by Silverfeelin** [comment]
That'll give you the source code. Please download the release instead.
